name: Docker Image CI

on:
  push:
    branches: [ "main" ]  # 或者你希望触发构建的分支
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.dingsiguo }}  # 使用您自己的用户名  1
          password: ${{ secrets.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 }} # 您的GitHub个人访问令牌(PAT)
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.dingsiguo }}/open-webui:${{ github.sha }}
            ghcr.io/${{ secrets.dingsiguo }}/open-webui:latest